apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres.cxoh5btbljf2.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: haro-cloud-dev
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: haro123@321haro
  URL: http://localhost:8100